package kudos.model;

public enum ActionType {
    KUDOS_GIVEN,
    CREATED_CHALLENGE,
    CANCELED_CHALLENGE,
    DECLINED_CHALLENGE,
    ACCEPTED_CHALLENGE,
    FAILED_CHALLENGE,
    MARKED_AS_COMPLETED,
    MARKED_AS_FAILED,
    ACCOMPLISHED_CHALLENGE,
    COMMENTED,
    STARTED_TO_FOLLOW,
    ADDED_NEW_IDEA
}
