package kudos.model;

public enum FeedType {
    KUDOS_GIVEN,
    CREATED_CHALLENGE,
    CANCELED_CHALLENGE,
    DECLINED_CHALLENGE,
    ACCEPTED_CHALLENGE,
    FAILED_CHALLENGE,
    MARKED_AS_COMPLETED,
    MARKED_AS_FAILED,
    ACCOMPLISHED_CHALLENGE,
    COMMENTED,
    REGISTERED_TO_OPENKUDOS,
    BIRTHDAY,
    WORK_ANNIVERSARY,
    STARTED_TO_FOLLOW,
    UNFOLLOWED,
    ADDED_NEW_IDEA
}
